from typing import Protocol, Self


class RingElem(Protocol):
    """
    Implements operations for an element of a mathematical ring.
    """
    def __add__(self, other: Self, /) -> Self: ...
    def __sub__(self, other: Self, /) -> Self: ...
    def __mul__(self, other: Self, /) -> Self: ...
    def __rmul__(self, other: Self, /) -> Self: ...
